git co master
git pull origin master
git co feature/01_hello_api
git rebase master
git push --force-with-lease
git co feature/2_prepare_models
git rebase feature/01_hello_api
git push --force-with-lease
git co feature/3_articles_api
git rebase feature/2_prepare_models
git push --force-with-lease
git co feature/4_article_api
git rebase feature/3_articles_api
git push --force-with-lease
git co feature/5_error_handling
git rebase feature/4_article_api
git push --force-with-lease
git co feature/6_authentications
git rebase feature/5_error_handling
git push --force-with-lease
git co feature/7_registrations
git rebase feature/6_authentications
git push --force-with-lease
git co feature/8_add_api_keys
git rebase feature/7_registrations
git push --force-with-lease
git co feature/9_add_api_key_auth
git rebase feature/8_add_api_keys
git push --force-with-lease
git co feature/10_add_article_crud
git rebase feature/9_add_api_key_auth
git push --force-with-lease
git co feature/11_add_request_spec_for_articles
git rebase feature/10_add_article_crud
git push --force-with-lease
git co feature/12_add_api_document
git rebase feature/11_add_request_spec_for_articles
git push --force-with-lease
